#!/bin/bash
if [ "$HOMEBREW_CELLAR" = "" ]; then 
	echo "HOMEBREW_CELLAR not set."
	exit
fi
allVer=$(ls -l $HOMEBREW_CELLAR/go $HOMEBREW_CELLAR/go@* |awk '{print $9}' |grep "^[0-9]\." |sort)
allRoots=$(find $HOMEBREW_CELLAR |grep "libexec" |grep "${HOMEBREW_CELLAR}/go" | awk '{split($0,a,"libexec"); print a[1]}' |uniq)
if [ "$#" = 1 ]; then
	if [ "$1" = "help" ]; then
	    echo "usage: gvm [GO_VERSION|help]"
	    echo "note: will switch Homebrew's 'go' to the highest version matching" 
	    echo "      GO_VERSION at the beginning of the version string. For "
	    echo "      example 1.17 will switch the current go binary to 1.17.X"
	    echo "      with maximum X available. Not passing GO_VERSION will switch"
	    echo "      to the highest version available."
	    echo "      To install another go version without removing the older ones:"
	    echo "      export HOMEBREW_NO_INSTALL_CLEANUP=1; brew install go@VERSION"
	    exit
	else 
		reqVer=$(echo "$allVer" |grep ^$1 |tail -n 1)
		if [ "$reqVer" = "" ]; then 
			echo "Version not found. Available versions: "$allVer
			exit
		fi
    fi 
fi
if [ "$#" = 0 ]; then
	reqVer=$(echo "$allVer" |tail -n 1)
fi
echo "Switching to $reqVer"
lnDest=$(echo "$allRoots" |grep $reqVer)bin/go
sudo rm /opt/homebrew/bin/go
sudo ln -s $lnDest /opt/homebrew/bin/go
